In [2]:
import numpy as np
#3. Fin^ the shape, size an^ ^imension of the following array?[[1, 2, 3, 4][5, 6, 7, 8],[9, 10, 11, 12]]
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [3]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [4]:
arr.shape

(3, 4)

In [5]:
arr.size

12

In [6]:
#4. Write python co^e to access the first row of the following array?[[1, 2, 3, 4][5, 6, 7, 8],[9, 10, 11, 12]]
arr[0]

array([1, 2, 3, 4])

In [12]:
#5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?[[1, 2, 3, 4][5, 6, 7, 8],[9, 10, 11, 12]]
arr[2,3]


12

In [15]:
#6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?[[1, 2, 3, 4][5, 6, 7, 8],[9, 10, 11, 12]]
arr[arr % 2==1]

array([ 1,  3,  5,  7,  9, 11])

In [25]:
#7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?
a=np.random.random((1,3,3))

In [26]:
a

array([[[0.2949048 , 0.73962896, 0.01923564],
        [0.20777244, 0.93601145, 0.05692106],
        [0.79887062, 0.2315227 , 0.83422194]]])

In [29]:
#8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?
a1=np.random.rand()
a2=np.random.randn()

In [30]:
a1

0.8981750885215228

In [31]:
a2

-0.6275213467556703

In [32]:
#9. Write co^e to increase the ^imension of the following array?[[1, 2, 3, 4][5, 6, 7, 8],[9, 10, 11, 12]]
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
arr.ndim

2

In [34]:
a3=np.random.random((2,3,3))

In [35]:
a3

array([[[0.58769652, 0.53492869, 0.62009383],
        [0.25255729, 0.46054375, 0.95037419],
        [0.84611089, 0.16370079, 0.47481984]],

       [[0.99960887, 0.74840909, 0.57091807],
        [0.63903117, 0.6685364 , 0.66720644],
        [0.57481221, 0.91726201, 0.43791944]]])

In [36]:
a3.ndim

3

In [37]:
#10. How to transpose the following array in NumPy?[[1, 2, 3, 4][5, 6, 7, 8],[9, 10, 11, 12]]
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [39]:
#11. Consi^er the following matrix:
#Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
#Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
#Perform the following operation using Python1
#,+ I(dex wiLe multiplicatio'
#1. Matix multiplicatio'
#2.Add both the maticK
#3. Subtact matix B om 
#4. Diide Matix B by A

In [62]:
A=np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
B=np.array([[1, 2, 3, 4] ,[5, 6, 7, 8],[9, 10, 11, 12]])

In [52]:
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
B

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
#1.
A*B

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [63]:
#2.
A@B

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [65]:
#3.
A+B

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [67]:
#4.
B - A

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [68]:
#5.
B / A

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [73]:
#12. Which function in Numpy can be use^ to swap the byte or^er of an array?
# Ans :- byteswap()

In [74]:
#13. What is the significance of the np.linalg.inv function?
x=np.array([[1,2],[3,4]])
y=np.linalg.inv(x)

In [75]:
x

array([[1, 2],
       [3, 4]])

In [76]:
y

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [84]:
#14. What ^oes the np.reshape function ^o, an^ how is it use^?
arr=np.array([[1,2,3,4,5,7]])

In [85]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 7]])

In [86]:
#15. What is broa^casting in Numpy?
#Ans: Broadcasting describe how numpy treats arrays with different shapes during arrithmetic operation.